[package]
name = "MtrBin"
version = "0.1.0"
edition = "2021"

[dependencies]
sled = "0.34.7"
ansi_term = "0.12.1"
rustyline = "14.0.0"
shellwords = "1.1.0"
chrono = "0.4.38"
tabled = "0.15.0"
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.118"
